language: android
jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1

sudo: false

script:
  - ./gradlew build

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle