language: android
jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1
    - extra-android-m2repository
    - extra-android-support

sudo: false

script:
  - ./gradlew build

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle