language: android
jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
    - extra-google-google_play_services

sudo: false

script:
  - ./build.sh

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle